# Generated by Django 5.0.3 on 2024-03-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('less', 'Less Difficult'), ('more', 'More Difficult')], max_length=10)),
                ('possible_answers', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
    ]
