# Generated by Django 5.0.3 on 2024-05-22 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_leaderboard_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={},
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 22, 21, 23, 25, 329024, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='time',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
